### ISSUE TITLE
Missing config.h

### ISSUE THREAD

**Issue by Nannk** [EUA/ESP32_LogicAnalyzer#7]
It might be my fault as im using lolin c3 mini and platformio core (cli).

**Comment by EUA** [comment]
<s>Yeah, please use Arduino 1.18.9... It's not compatible with Arduino-IDE, yet...</s>

Edit: ESP32-C3 chips are not supported. Their internal I2S DMA code is different. Can't use the DMA with them.
Might be support by manual ASM...

**Comment by Nannk** [comment]
Thank you, it makes sense now
